### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by wcollins-ebsco** [grantjenks/python-wordsegment#13]
using wordsegment-1.1.6-py2.py3-none-any.whl

>>> import wordsegment as ws
>>> seg=ws.Segmenter()
>>> seg.score('industry','oil')
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    seg.score('industry','oil')
  File "C:\Python3\lib\site-packages\wordsegment\__init__.py", line 108, in score
    return self.score(word)
  File "C:\Python3\lib\site-packages\wordsegment\__init__.py", line 93, in score
    return 10.0 / (total * 10 ** len(word))
ZeroDivisionError: float division by zero

**Comment by grantjenks** [comment]
Call seg.load() before seg.score()

**Comment by wcollins-ebsco** [comment]
Thank you!
